### ISSUE TITLE
[Bug]Bot currently unable to retrieve stock information due to an issue with the yfinance library

### ISSUE THREAD

**Issue by SamZhang02** [SamZhang02/STONK#1]
The bot is currently not working due to [an issue with the yfinance library](https://github.com/ranaroussi/yfinance/issues/1291). If the issue does not get fixed in the near future, I will be changing the underlying algorithm to retrieve stock informtion.

**Comment by alimjahagirdar** [comment]
Hi, I am working on a project, and I am facing this issue '' TypeError: string indices must be integers, not 'str' '' and am unable to retrieve stock data.  do you have any suggestions for me on how I can solve this issue?

**Comment by SamZhang02** [comment]
You can refer to the link in my original description to take a look at the issue I opened in the yfinance repo. It is a problem currently impacting everyone.

It should be fixed soon, someone just requested a PR a few hours ago to fix this issue.

**Comment by alimjahagirdar** [comment]
Thanks a lot, I was worried about it ..hope it gets fixed soon.

alim khan

**Comment by SamZhang02** [comment]
Issue has been fixed on yfinance's side, the bot is now back to working.

**Comment by alimjahagirdar** [comment]
Hi, Are you facing a new issue with yfinance  “yahoo has again changed data format ..decryption ” . On 15-Jan-2023, at 5:26 PM, Sam Zhang ***@***.***> wrote:﻿
Closed #1 as completed.
